### ISSUE TITLE
ik weet niet hoe te beginnen met testen

### ISSUE THREAD

**Issue by stgm** [Zuurve01/Eindproject_data#2]
neem even wat korte instructies op in de README, waar moet ik zijn, welke browser gebruiken e.d.

**Comment by Zuurve01** [comment]
Ik loop er morgen nog wel even doorheen, ik zorg dat ie aan het eind van de dag gesloten wordt en helemaal af is.Verzonden vanaf mijn Huawei mobiele telefoon-------- Oorspronkelijk bericht --------Onderwerp: [Eindproject_data] ik weet niet hoe te beginnen met testen (#2)Van: Martijn Stegeman Aan: Zuurve01/Eindproject_data Cc: neem even wat korte instructies op in de README, waar moet ik zijn, welke browser gebruiken e.d.
